### ISSUE TITLE
Using HTTP in development mode produces errors

### ISSUE THREAD

**Issue by gedw99** [johanbrandhorst/grpcweb-example#15]
cd /Users/apple/workspace/go/src/github.com/johanbrandhorst/grpcweb-example && go run main.go
INFO[2018-02-15T08:35:36.242571+01:00] Serving on https://localhost:10000
2018/02/15 08:35:40 http: TLS handshake error from 127.0.0.1:50771: tls: first record does not look like a TLS handshake

**Comment by gedw99** [comment]
https://127.0.0.1:10000/ works but needs a cert.

1. Automatic redirect to https 
2. CMD to install cert to browser. Saw golang code for this somewhere.

**Comment by johanbrandhorst** [comment]
Hi, thanks for the issue report!

As you noticed, this happens if you navigate to http://localhost:10000 instead of https://localhost:10000. Personally, I don't consider this too much of a problem as the URL you _should_ be using for development is clearly listed, and adding extra bloat to the server for this rare use case is just unnecessary.

As for installing the cert int the browser, I don't know how to do this via Go, but again, this is just a problem for development mode and I don't think it matters all that much. Personally I just ignore the certificate problem since I know I'm running it on my local machine.

**Comment by gedw99** [comment]
Fair enough.. I will then add it to the CI repo.
I need the Self signed Cert to work because:
-  i run everything through VPN and webviews on Desktop and Mobile.
-  E2E tests need it.

**Comment by johanbrandhorst** [comment]
Sure, I'm not saying you can't decide to trust the self signed cert, but it's a pretty specific use case, and a general solution probably won't be necessary.

**Comment by gedw99** [comment]
In the end i went with Cloudlare Warp.

https://www.cloudflare.com/products/cloudflare-warp/
https://github.com/caddyserver/cloudflare-warp-plugin
- Provides a secure tunnel to on premsie servers without exposing the IP and no local ports to open !

**Comment by johanbrandhorst** [comment]
Cool, sounds like the same as https://ngrok.com/
