### ISSUE TITLE
cannot find package "github.com/gorilla/websocket" in any of:

### ISSUE THREAD

**Issue by timotheecour** [johanbrandhorst/grpcweb-example#19]
go run main.go
main.go:14:2: cannot find package "github.com/gorilla/websocket" in any of:
        /Users/timothee/homebrew/Cellar/go/1.10.2/libexec/src/github.com/gorilla/websocket (from $GOROOT)
        /Users/timothee/go/src/github.com/gorilla/websocket (from $GOPATH)

I had to do:
```
go get github.com/gorilla/websocket
go get github.com/improbable-eng/grpc-web/go/grpcweb
go get github.com/johanbrandhorst/grpcweb-example/client/compiled
go get github.com/lpar/gzipped
go get github.com/sirupsen/logrus
```
could these instructions be added to readme? are these the correct instructions?

**Comment by johanbrandhorst** [comment]
That's weird, it's definitely in the vendor directory. How did you check it out?

**Comment by johanbrandhorst** [comment]
I see you edited your original query, no, that is not the correct thing to be doing, if you've cloned the repo with the vendor folder everything should build automatically. Can you tell me how you cloned the repo?

**Comment by timotheecour** [comment]
```
cd mydir
git clone https://github.com/johanbrandhorst/grpcweb-example
cd grpcweb-example
go run main.go
```

**Comment by johanbrandhorst** [comment]
The `vendor` directory is located in the same folder as `main.go`. I'm wondering if you perhaps cloned the repo outside of teh $GOPATH? You'll need to make sure you clone the repo to the appropriate path in the $GOPATH structure.

How about you try and go-get the project instead?

```bash
$ go get -u github.com/johanbrandhorst/grpcweb-example
```
Then you should be able to run `grpcweb-example` and it will host the site for you. It will also clone it into the right place (`$GOPATH/src/github.com/johanbrandhorst/grpcweb-example`).

**Comment by timotheecour** [comment]
> The vendor directory is located in the same folder as main.go

right, but main.go references `github.com/gorilla/websocket`, not `vendor/github.com/gorilla/websocket` , so not sure how it could guess to look inside vendor

>  I'm wondering if you perhaps cloned the repo outside of teh $GOPATH

as mentioned above, my GOPATH is empty

> How about you try and go-get the project instead?

just did, it did create `/Users/timothee/go/bin/grpcweb-example` , woohoo!
however: it'd be nice to not have to do this (eg if i don't want to affect what's inside ~/go, or if I want to work on multiple forks of grpcweb-example) and it'd build locally wherever I git clone to (may i need to set GOPATH to something ? the clone repo root folder?)

*  bin/grpcweb-example
INFO[2018-05-04T15:05:59.976172151-07:00] Serving on https://localhost:10000
FATA[2018-05-04T15:05:59.979112255-07:00] open ./insecure/cert.pem: no such file or directory

**Comment by johanbrandhorst** [comment]
The last error is because you need to generate some self-signed certs first:

```bash
$ make generate_cert
```
https://github.com/johanbrandhorst/grpcweb-example/blob/master/Makefile#L18.

You'll need to run the binary from somewhere that has access to those generated certs, like the root of the repository (`~/go/src/github.com/johanbrandhorst/grpcweb-example/`). Or, you can specify your own cert and key if you have those available.

On the point about not modifying the $GOPATH, I'm afraid you're out of luck as long as you want to use Go ;). There are various tools for managing different versions of libraries, but it's definitely outside the scope of this repo. I encourage you to google around and learn about the $GOPATH. This will also explain the concept of the vendor folder.

I'm going to close this as the root of the issue was the unorthodox cloning of the repo. Sorry if this is your first Go project, but you simply need to be using the GOPATH for anything to be working as expected.

**Comment by johanbrandhorst** [comment]
Yeh, it's a self signed certificate. You're welcome to use whichever certificate you like, and the example also supports using Lets Encrypt. It's running on https://grpcweb.jbrandhorst.com using Let's Encrypt for certificate issuing.
